### ISSUE TITLE
Image not rendering on CMS PD/PD website

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/CYF-PD#23]
**Steps to reproduce**
1. Create a bock
2. Add an image to one of the content boxes

Expected outcome
- Be able to view the image correctly

Current outcome
-
![image](https://github.com/CodeYourFuture/CYF-PD/assets/80272258/de148260-9233-4046-8760-79086cc88ea8)
Page: https://cyf-pd.netlify.app/blocks/prep-teamwork-project/readme/

Linked to [PR for the Curriculum](https://github.com/CodeYourFuture/curriculum/issues/222)

**Comment by SallyMcGrath** [comment]
Just writing out my investigation process here as I don't have time to do any more as I've mega deadlines:

It looks like this image exists in the preview but not on the front end of cyf-pd

The preview is accessing this blob store blob:https://cyf-pd.netlify.app/a1ebc9d4-6c32-43a6-a22b-8d9717faa792. Blob assets are created within the browser session and cannot be accessed outside that session.

In order to make this image accessible, we need to save it out to a dir. 
It seems like this cms has a media library as there's a way to upload images to it, and this image persists across sessions. So it's somewhere! 

On the front end the src is teamwork-project.png and this link is broken.

I searched the codebase for that image and it's stored correctly as a bundle asset in the block folder https://github.com/CodeYourFuture/CYF-PD/blob/main/content/blocks/prep-teamwork-project/teamwork-project.png

It's right here https://cyf-pd.netlify.app/blocks/prep-teamwork-project/teamwork-project.png

So there are two separate things to resolve:

1. fix the link on the pd site so the stored image shows correctly
2. parse that link on the curriculum so the stored image is hotlinked OR pull it with the floated image pull strategy from
