### ISSUE TITLE
Grammarly to be supported by PD CMS

### ISSUE THREAD

**Issue by kfklein15** [CodeYourFuture/CYF-PD#36]
AS A PD Volunteer
I WANT to be able to review my text a final time on the CMS using Grammarly
SO THAT I can ensure we reduce English errors

**Acceptance criteria**
* Grammarly should run on any of the fields of the CMS

**Tech Notes**
I ran the test Grammarly [suggests](https://support.grammarly.com/hc/en-us/articles/115000090392-I-do-not-see-the-G-icon-on-a-certain-web-page-or-in-a-certain-text-field-but-see-it-on-other-web-pages#:~:text=other%20web%20pages-,I%20do%20not%20see%20the%20G%20icon%20on%20a%20certain,box%20is%20incompatible%20with%20Grammarly.), in order to identify that is wasn't supported
<img width="546" alt="image" src="https://github.com/CodeYourFuture/CYF-PD/assets/80272258/9e72d71a-ff87-4968-a982-245fdac971b3">

**Comment by SallyMcGrath** [comment]
Hi @kfklein15 

It looks to me that this [only happens when you choose markdown](https://github.com/decaporg/decap-cms/issues/4737) instead of Rich text. Can you confirm/disconfirm?

I tested this with Grammarly desktop and it seems to work with Rich text, though it's a bit flaky and I'll look into it at some point. It doesn't look like we're blocking it, though. It looks like Grammarly itself is struggling to identify nested contenteditable windows.

**Comment by kfklein15** [comment]
Hi @SallyMcGrath , I have the same problem on both markdown and rich text: the changes from Grammarly aren't applied to it, so I have to re-type any change. I made this video, which hopefully helps explain it.

https://github.com/CodeYourFuture/CYF-PD/assets/80272258/d86deb39-ad0e-49d5-be0f-57263f7aa53b

**Comment by martinjagodic** [comment]
Grammarly works for me until I add an editor component. Does anybody experience the same problem? Using Decap 3.0.12

**Comment by SallyMcGrath** [comment]
@kfklein15  Grammarly is working now on Decap 3 but not on nested editors. I am considering switching out Decap for another fork of the same code called Static CMS. Here's a preview #53

**Comment by kfklein15** [comment]
Ok, I will then close this ticket since we'll follow it on 53.
